command: ['npm', 'run', 'start']
env:
  - name: DATABRICKS_SERVING_ENDPOINT_NAME
    valueFrom: agents-serving-endpoint
  - name: DATABRICKS_WAREHOUSE_ID
    valueFrom: sql-warehouse
  - name: DATABRICKS_VECTOR_SEARCH_INDEX_NAME
    valueFrom: support-docs-index
