// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    customer_history: {
        name: "customer_history";
        parameters: {
          /** STRING - use sql.string() */
          customer_id: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          interaction_id: string;
          /** @sqlType TIMESTAMP */
          interacted_at: string;
          /** @sqlType STRING */
          issue_category: string;
          /** @sqlType STRING */
          issue_description: string;
          /** @sqlType STRING */
          agent_id: string;
        }>;
      };
    customer_orders: {
        name: "customer_orders";
        parameters: {
          /** STRING - use sql.string() */
          customer_id: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          transaction_id: string;
          /** @sqlType TIMESTAMP */
          ordered_at: string;
          /** @sqlType STRING */
          delivery_address: string;
          /** @sqlType STRING */
          product_id: string;
          /** @sqlType STRING */
          product_name: string;
          /** @sqlType STRING */
          product_category: string;
          /** @sqlType STRING */
          product_sub_category: string;
        }>;
      };
    interaction_detail: {
        name: "interaction_detail";
        parameters: {
          /** STRING - use sql.string() */
          interaction_id: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          interaction_id: string;
          /** @sqlType TIMESTAMP */
          interacted_at: string;
          /** @sqlType STRING */
          issue_category: string;
          /** @sqlType STRING */
          issue_description: string;
          /** @sqlType STRING */
          agent_id: string;
          /** @sqlType STRING */
          customer_id: string;
          /** @sqlType STRING */
          customer_name: string;
          /** @sqlType STRING */
          email: string;
          /** @sqlType STRING */
          phone: string;
          /** @sqlType STRING */
          address: string;
          /** @sqlType STRING */
          customer_level: string;
        }>;
      };
    recent_interactions: {
        name: "recent_interactions";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          interaction_id: string;
          /** @sqlType TIMESTAMP */
          interacted_at: string;
          /** @sqlType STRING */
          issue_category: string;
          /** @sqlType STRING */
          issue_description: string;
          /** @sqlType STRING */
          agent_id: string;
          /** @sqlType STRING */
          customer_id: string;
          /** @sqlType STRING */
          customer_name: string;
          /** @sqlType STRING */
          customer_level: string;
        }>;
      };
    support_sources: {
        name: "support_sources";
        parameters: {
          /** STRING - use sql.string() */
          query_text: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          document_id: string;
          /** @sqlType STRING */
          source_type: string;
          /** @sqlType STRING */
          source_id: string;
          /** @sqlType STRING */
          title: string;
          /** @sqlType STRING */
          content: string;
          /** @sqlType STRING */
          source_uri: string;
        }>;
      };
  }
}
